#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

$app = new Symfony\Component\Console\Application('Beanstalk Migrate', '1.0');
$app->add(new Beanstalk\Migrate\Commands\MigrateAll);

$app->run();